# Generated by Django 2.0.2 on 2018-05-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('ol_id', models.CharField(max_length=16, unique=True)),
                ('alternate_names', models.CharField(blank=True, max_length=1024)),
                ('year_of_birth', models.CharField(blank=True, max_length=50)),
                ('year_of_death', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'Author',
                'ordering': ['name'],
            },
        ),
    ]
